### ISSUE TITLE
Test remindme

### ISSUE THREAD

**Issue by Qix-** [Qix-/devnull#1]
@RemindMe 30 seconds

**Comment by Qix-** [comment]
@RemindMe 10 seconds

**Comment by Qix-** [comment]
@RemindMe in 30 seconds

**Comment by RemindMe** [comment]
No.

**Comment by Qix-** [comment]
@RemindMe hi

**Comment by RemindMe** [comment]
Yo

**Comment by Qix-** [comment]
@RemindMe in 5 days

**Comment by Qix-** [comment]
@RemindMe in 10 hours

**Comment by Qix-** [comment]
@RemindMe 60 seconds

**Comment by Qix-** [comment]
@RemindMe 20 seconds

**Comment by Qix-** [comment]
@RemindMe  50 seconds

**Comment by Qix-** [comment]
@RemindMe in 16 hours

**Comment by Qix-** [comment]
@RemindMe in 10 minutes

**Comment by Qix-** [comment]
@RemindMe 10 minutes

**Comment by Qix-** [comment]
@RemindMe in 10 seconds

**Comment by Qix-** [comment]
@RemindMe in 10 seconds

**Comment by Qix-** [comment]
@RemindMe tomorrow
@RemindMe I love you

**Comment by Qix-** [comment]
@RemindMe thanks!

**Comment by Qix-** [comment]
@RemindMe aisdjfaisjdfiajsdfijasd

**Comment by RemindMe** [comment]
Terribly sorry, but I didn't understand that. :flushed:
I don't quite understand _"aisdjfaisjdfiajsdfijasd"_. Care to try again?

**Comment by Qix-** [comment]
@RemindMe sdkfjaskdjfas
@RemindMe adsijaisdjf

**Comment by RemindMe** [comment]
I didn't quite catch that. :frowning:
I don't quite understand _"aisdjfaisjdfiajsdfijasd"_. Care to try again?

**Comment by RemindMe** [comment]
I didn't quite catch that. :frowning:

The following didn't make sense to me:
- sdkfjaskdjfas
- adsijaisdjf

**Comment by Qix-** [comment]
@RemindMe in 10 seconds to smell the flower
@RemindMe aosdhfoashdfoa

**Comment by RemindMe** [comment]
Hmm, something's not right there. :persevere:
I don't quite understand _"aosdhfoashdfoa"_. Care to try again?

**Comment by Qix-** [comment]
@RemindMe ohai

**Comment by RemindMe** [comment]
Hmm, something's not right there. :persevere:
I don't quite understand _"aosdhfoashdfoa"_. Care to try again?

**Comment by RemindMe** [comment]
Terribly sorry, but I didn't understand that. :flushed:
I don't quite understand _"ohai"_. Care to try again?

**Comment by Qix-** [comment]
@RemindMe in 10 seconds to commit your username detection fix.

**Comment by Qix-** [comment]
@RemindMe aksdjfaksjd

**Comment by Qix-** [comment]
@RemindMe sdkfjaksdjfaksdfjadsjfajsdfjasjdf

**Comment by RemindMe** [comment]
I didn't quite catch that. :frowning:
I don't quite understand _"aksdjfaksjd"_. Care to try again?

**Comment by RemindMe** [comment]
I didn't quite catch that. :frowning:
I don't quite understand _"sdkfjaksdjfaksdfjadsjfajsdfjasjdf"_. Care to try again?

**Comment by Qix-** [comment]
@RemindMe in 19 seconds to clean up
@RemindMe on the fourth solstice to do witchcraft.

**Comment by RemindMe** [comment]
Hmm, not sure what you meant there. :no_mouth:
I don't quite understand _"on the fourth solstice"_. Care to try again?

**Comment by Qix-** [comment]
@RemindMe tomorrow to add mongo tracking and such.

**Comment by Qix-** [comment]
@RemindMe tomorrow
@RemindMe asdkjfaksdfjkasdjkfjkasdjk
@RemindMe in 4 days
@RemindMe I love you

**Comment by RemindMe** [comment]
Hmm, not sure what you meant there. :no_mouth:

I don't quite understand _"asdkjfaksdfjkasdjkfjkasdjk"_. Care to try again?

However, I scheduled the other 2 reminders for you! :dancer:

**Comment by Qix-** [comment]
@RemindMe Thanks!

**Comment by Qix-** [comment]
@RemindMe next friday to party hardy.

**Comment by Qix-** [comment]
@RemindMe kjafskdjfalsjkdf

**Comment by RemindMe** [comment]
Terribly sorry, but I didn't understand that. :flushed:

I don't quite understand _"kjafskdjfalsjkdf"_. Care to try again?

**Comment by Qix-** [comment]
This is some text.

And now a gif.

![](https://media1.giphy.com/media/tT0wtdSJvE0Rq/giphy.gif?response_id=59204098e87992a02e46459b)

@RemindMe I love you

Also, there is a thing I need to do. Later, though.

@RemindMe tomorrow to buy groceries.

That concludes the regex search test.

**Comment by Qix-** [comment]
@RemindMe flub
@RemindMe tomorrow
@RemindMe i love you
@RemindMe blippppppppp
@RemindMe 123456
@RemindMe yesterday
@RemindMe thanks!
@RemindMe nope
@RemindMe tomorrow to eat breakfast
@RemindMe in 16 days to do a commit.
@RemindMe in a year to check back on this.
@RemindMe on July 17th to look at this post again.
@RemindMe now
@RemindMe later
@RemindMe -1

**Comment by RemindMe** [comment]
Hmm, not sure what you meant there. :no_mouth:

The following didn't make sense to me:
- flub
- blippppppppp
- 123456
- yesterday
- nope
- now
- later
- -1

However, I scheduled the other 5 reminders for you! :dancer:

**Comment by Qix-** [comment]
@RemindMe @RemindMe 

Oh shi-..

**Comment by RemindMe** [comment]
Hmm, not sure what you meant there. :no_mouth:

I don't quite understand _"@RemindMe"_. Care to try again?

**Comment by Qix-** [comment]
@RemindMe

**Comment by Qix-** [comment]
@RemindMe tomorrow

**Comment by Qix-** [comment]
@RemindMe

**Comment by RemindMe** [comment]
Hey there, @Qix-! I'm __RemindMe__, a robot that helps you remember to do things here on GitHub.

If you need to remember something, mention me with a time and (optionally) a reminder.

Some examples of things I respond to:
- _@RemindMe in 4 hours to check up on this PR._
- _@RemindMe tomorrow to come back to this issue._
- _@RemindMe on July 3rd to do a release._
- _@RemindMe a year from today to update the copyright notice._

If all of the reminders in your comment are OK, I'll simply respond with a :+1: thumbs up. Otherwise, I'll let you know what I didn't understand.

Then when the time comes, I'll ping and remind you to come back and have a look! :metal:

**Comment by Qix-** [comment]
@RemindMe ?

**Comment by RemindMe** [comment]
Hey there, @Qix-! I'm __RemindMe__, a robot that helps you remember to do things here on GitHub.

If you need to remember something, mention me with a time and (optionally) a reminder.

Some examples of things I respond to:
- _@RemindMe in 4 hours to check up on this PR._
- _@RemindMe tomorrow to come back to this issue._
- _@RemindMe on July 3rd to do a release._
- _@RemindMe a year from today to update the copyright notice._

If all of the reminders in your comment are OK, I'll simply respond with a :+1: thumbs up. Otherwise, I'll let you know what I didn't understand.

Then when the time comes, I'll ping and remind you to come back and have a look! :metal:

**Comment by Qix-** [comment]
@RemindMe

**Comment by Qix-** [comment]
@RemindMe Tomorrow

**Comment by RemindMe** [comment]
Hey there, @Qix-! I'm __RemindMe__, a robot that helps you remember to do things here on GitHub.

If you need to remember something, mention me with a time and (optionally) a reminder.

Some examples of things I respond to:
- _@RemindMe in 4 hours to check up on this PR._
- _@RemindMe tomorrow to come back to this issue._
- _@RemindMe on July 3rd to do a release._
- _@RemindMe a year from today to update the copyright notice._

If all of the reminders in your comment are OK, I'll simply respond with a :+1: thumbs up. Otherwise, I'll let you know what I didn't understand.

Then when the time comes, I'll ping and remind you to come back and have a look! :metal:

**Comment by RemindMe** [comment]
Hey there, @Qix-! I'm __RemindMe__, a robot that helps you remember to do things here on GitHub.

If you need to remember something, mention me with a time and (optionally) a reminder.

Some examples of things I respond to:
- _@RemindMe in 4 hours to check up on this PR._
- _@RemindMe tomorrow to come back to this issue._
- _@RemindMe on July 3rd to do a release._
- _@RemindMe a year from today to update the copyright notice._

If all of the reminders in your comment are OK, I'll simply respond with a :+1: thumbs up. Otherwise, I'll let you know what I didn't understand.

Then when the time comes, I'll ping and remind you to come back and have a look! :metal:

**Comment by Qix-** [comment]
@RemindMe

**Comment by Qix-** [comment]
@RemindMe tomorrow

**Comment by RemindMe** [comment]
Hey there, @Qix-! I'm __RemindMe__, a robot that helps you remember to do things here on GitHub.

If you need to remember something, mention me with a time and (optionally) a reminder.

Some examples of things I respond to:
- _@RemindMe in 4 hours to check up on this PR._
- _@RemindMe tomorrow to come back to this issue._
- _@RemindMe on July 3rd to do a release._
- _@RemindMe a year from today to update the copyright notice._

If all of the reminders in your comment are OK, I'll simply respond with a :+1: thumbs up. Otherwise, I'll let you know what I didn't understand.

Then when the time comes, I'll ping and remind you to come back and have a look! :metal:

**Comment by Qix-** [comment]
@RemindMe

**Comment by Qix-** [comment]
@RemindMe tomorrow to cry

**Comment by Qix-** [comment]
@RemindMe hello?

**Comment by Qix-** [comment]
@RemindMe whatawhatasdkjaksdjfaksdjf

**Comment by Qix-** [comment]
@RemindMe tomorrow

**Comment by Qix-** [comment]
@RemindMe oops it's locked yo
